version: "2.2"

services:
  connector:
      image: https://registry.gitlab.com/herlix/learn:0.0.0.1
      container_name: learn-nodejs
      hostname: learn-nodejs
      environment:
        - "PORT=80"
      ports:
        - "80:3978"
